<a href="https://colab.research.google.com/github/Suman5501/AI-lab-assignment/blob/main/7_CSL5402.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

LAB-07 Assignment (CSL5402)
---

Q1.  WAP to classify the type of flower. The features of the flower type are givenin the iris dataset format. To perform this task, students can only use the SVMclassifier.Report the accuracy difference between different kernels (Poly, linear,RBF) on iris.

Q 2.  WAP to classify the purchase of a social media user with features such as:

UserID    Gender    Age   Estimated_Salary   Purchased

---




12345678  Female    82       1900000          ?


---

12345679  Male      78       20               ?

---


The dataset is in social_advformat and students should only use the SVMclassifier. Report the classification result with Poly and RBF kernel.

In [5]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
data = pd.read_csv('/iris.csv')
data.head(10)

sepal_length  sepal_width  petal_length  petal_width  plant
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.6           1.4          0.2      0
5           5.4          3.9           1.7          0.4      0
6           4.6          3.4           1.4          0.3      0
7           5.0          3.4           1.5          0.2      0
8           4.4          2.9           1.4          0.2      0
9           4.9          3.1           1.5          0.1      0

In [8]:
data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'plant'], dtype='object')

In [9]:
X = data[['sepal_length','sepal_width','petal_length','petal_width']]
y = data['plant']

In [11]:
from sklearn.model_selection import train_test_split
x_train , x_test ,y_train, y_test = train_test_split(X,y,test_size=0.2)
model1 = SVC(kernel='rbf')
model2 = SVC(kernel='poly')
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model1_pred = model1.predict(x_test)
model2_pred = model2.predict(x_test)

In [12]:
model1_pred

array([0, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 0, 0, 1, 1, 2, 1, 0, 0, 2, 1,
       2, 0, 0, 1, 1, 1, 0, 0])

In [13]:
model2_pred

array([0, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 0, 0, 1, 1, 2, 1, 0, 0, 2, 2,
       2, 0, 0, 1, 1, 1, 0, 0])

In [14]:
from sklearn.metrics import accuracy_score
print("Accuracy with RBF =",accuracy_score(y_test,model1_pred))
print("Accuracy with Poly =",accuracy_score(y_test,model2_pred))

Accuracy with RBF = 0.9333333333333333
Accuracy with Poly = 1.0


In [ ]:
data = pd.read_csv('/content/Social_Network_Ads.csv')
data.head(10)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
5  15728773    Male   27            58000          0
6  15598044  Female   27            84000          0
7  15694829  Female   32           150000          1
8  15600575    Male   25            33000          0
9  15727311  Female   35            65000          0

In [ ]:
data.columns

Index(['User ID', 'Gender', 'Age', 'EstimatedSalary', 'Purchased'], dtype='object')

In [ ]:
def convert(gender):
 if gender == "Male":
   return 1
 elif gender == "Female":
   return 0

In [ ]:
data['Gender'] = data['Gender'].apply(convert)
data['Gender'].head(10)

0    1
1    1
2    0
3    0
4    1
5    1
6    0
7    0
8    1
9    0
Name: Gender, dtype: int64

In [ ]:
X = data[['Gender', 'Age', 'EstimatedSalary']]
y = data['Purchased']
x_train , x_test ,y_train, y_test = train_test_split(X,y,test_size=0.2)
model1 = SVC(kernel='rbf')
model2 = SVC(kernel='poly')
model1.fit(x_train,y_train)
model2.fit(x_train,y_train)
model1_predict = model1.predict(x_test)
model2_predict = model2.predict(x_test)

In [ ]:
model1_predict

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0])

In [ ]:
model2_predict

array([0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0])

In [ ]:
print("Accuracy with RBF =",accuracy_score(y_test,model1_predict))
print("Accuracy with Poly =",accuracy_score(y_test,model2_predict))

Accuracy with RBF = 0.8125
Accuracy with Poly = 0.8125
